// packages/tasks-with-mobx/src/components/TaskItem/index.tsx
import { useState } from "react";
import { type Task } from "@efanworks/tasks-types";
import { useTasks } from "../../store/tasks";
import { observer } from "mobx-react-lite";

export const TaskItem = observer(({ task }: { task: Task }) => {
  const [editing, setEditing] = useState(false);
  const [value, setValue] = useState(task.text);
  const { changeTask, deleteTask } = useTasks();

  const handleSave = async () => {
    await changeTask(task.id, value);
    setEditing(false);
  };

  return (
    <li>
      {editing ? (
        <>
          <input
            type="text"
            value={value}
            onChange={(e) => setValue(e.target.value)}
          />
          <button onClick={handleSave}>save</button>
        </>
      ) : (
        <>
          {task.text} - {task.done ? "done" : "undo"}
          <button onClick={() => setEditing(true)}>edit</button>
        </>
      )}
      <button onClick={() => deleteTask(task.id)}>delete</button>
    </li>
  );
});

// packages/tasks-with-pinia/src/components/TaskItem/index.vue
<script setup lang="ts">
import { ref } from "vue";
import { type Task } from "@efanworks/tasks-types";
import { useTasksStore } from "../../store";

const { task } = defineProps<{
  task: Task;
}>();
const editing = ref(false);
const value = ref(task.text);
const { changeTask, deleteTask } = useTasksStore();

const handleSave = async () => {
  await changeTask(task.id, value.value);
  editing.value = !editing.value;
};
</script>

<template>
  <li>
    <template v-if="editing">
      <input
        type="text"
        :value="value"
        @input="(e) => (value = (e.target as HTMLInputElement).value)"
      />
      <button @click="handleSave">save</button>
    </template>
    <template v-else>
      {{ task.text }} - {{ task.done ? "done" : "undo" }}
      <button @click="() => (editing = !editing)">edit</button>
    </template>
    <button @click="() => deleteTask(task.id)">delete</button>
  </li>
</template>
