// packages/tasks-with-redux/src/components/AddTask/index.tsx
import { useState } from "react";
import {useAppDispatch } from '../../store';
import { addTask } from "../../store/tasksSlice";

export const AddTask = () => {
  const [newTaskText, setNewTaskText] = useState("");
  const dispatch = useAppDispatch();

  const handleAddTask = async () => {
    await dispatch(addTask(newTaskText));
    setNewTaskText("");
  };

  return (
    <>
      <input
        type="text"
        value={newTaskText}
        onChange={(e) => setNewTaskText(e.target.value)}
      />
      <button onClick={handleAddTask}>add</button>
    </>
  );
};

// packages/tasks-with-pinia/src/components/AddTask/index.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useTasksStore } from '../../store';

const newTaskText = ref("");
const store = useTasksStore();

const handleTextChange = (e: InputEvent) => {
  const target = e.target as HTMLInputElement;
  newTaskText.value = target.value;
};

const handleAddTask = async () => {
  if (newTaskText.value.trim()) {
    await store.addTask(newTaskText.value);
    newTaskText.value = "";
  }
};
</script>

<template>
  <input type="text" :value="newTaskText" @input="handleTextChange" />
  <button @click="handleAddTask">add</button>
</template>
